### ISSUE TITLE
Media folder not created properly

### ISSUE THREAD

**Issue by PhyxionNL** [Jumoo/uSync.Complete.Issues#197] opened 2023-03-24 13:36 UTC
**Describe the bug**

**Version (please complete the following information):**
 - Umbraco Version: 11.2.1
 - uSync.Complete Version: 11.0.2

**To Reproduce**
1. Create under Media a folder such as: Files\Temp\Placeholder\20.20.
2. Upload some file to "20.20".
3. Refer to this file in a new document.
4. Sync parent containing the document to destination.
5. What happens is that "20.20" isn't created, and the file is uploaded under "Placeholder".
6. It might be required to also remove an existing - but differently named - folder AND a file with the same name as the uploaded file under "Placeholder" before syncing. See below for more details.

The additional steps I do:
1. Go to Files\Temp\Placeholder\ and remove "20.10". **Also remove it from trash.**
2. See above 1-3 instructions.
3. Go to the document that referred to the file you removed in "20.10", and "clear" the file there as well, then save the document.
4. Now sync the parent containing the documents.

Document structure under Content:
Folder\Doc1 -- old - now removed media item
Folder\Doc2 -- newly added with newly added media item
Doc1 and Doc2 have the same document type and refer to a different media item.

**Comment by KevinJump** [comment] 2023-03-24 15:04
Yeah, I can confirm i can reproduce this, 

i think there is something going astray in the dependency calculations for the parent folders of the media items.

**Comment by KevinJump** [comment] 2023-03-24 15:19
Hi, 

It looks like the issue is with the caching layer in uSync.Complete. We will fix this.

if in the meantime you need a workaround disabling caching by adding the below to the "uSync" section of your appsetting.json file will fix the issue.

```json
"Complete": {
      "Caching": {
        "Enabled": false
      }
    },  
```

**Comment by PhyxionNL** [comment] 2023-03-24 15:37
Thanks, until it's fixed I can move the file myself. Luckily I don't have to do this too often.
Just curious, is the 6th step required? 🙂

**Comment by KevinJump** [comment] 2023-03-24 19:58
Fix in a nightly build (not stable, for production, etc etc)

https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync.Complete/overview/11.0.3-build.20230324.1

I think you would also have to rebuild the uSync cache to test this (Publisher dashboard, cache in the top right hand corder).

- for release we might put a cache rebuild in as part of the upgrade - but we will need to test it in terms of performance (big site = slow rebuild)

**Comment by KevinJump** [comment] 2023-03-24 19:59
_just to add next release - wont actually be months, prob in next 10 days._

**Comment by KevinJump** [comment] 2023-03-29 11:15
Fixed in uSync.Compelte/uSync v11.1 (released)

**Closed as completed by KevinJump** 2023-03-29 11:15 UTC
Labels: uSyncPublisher
